// Project Euler - Problem 012 - https://projecteuler.net/problem=12
// Code by Douglas Costa - 25/07/2017

/*
Problem 12 
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors? */

#include <stdio.h>
#include <stdlib.h>

int divisors(long int n);

int main(){
    long int count=0,i,num=0;
    int ndiv;
    while(1){
        count+=1;
        num=0;
        for(i = 0 ; i <= count ; i++){
            num+=i;
        }
        ndiv = divisors(num);
        
        if (ndiv >= 500) {
            printf("\n\n%ld - %d\n\n",num,ndiv);
            exit(1);
        }    
    }
}

int divisors(long int n){
    long int i=0, ndiv=0;
    if (n != 1){
        for(i = 1 ; i <= n ; i++){
            if (n % i == 0) ndiv+=1;
        }
    }
    return ndiv;
}